### ISSUE TITLE
[Feature]: Reduced memory requirements

### ISSUE THREAD

**Issue by outpaddling** [ghostbsd/ghostbsd-src#123]
### Describe the feature or enhancement request

I think it would be valuable to significantly reduce the memory requirements for GhostBSD, for the sake of people who just want to try it out in a virtual machine using a PC with only 4 GiB of RAM.

GhostBSD XFCE doesn't really seem to need much more than 1 after it's installed and running.
![GhostBSD](https://user-images.githubusercontent.com/11299711/141998320-db47b15b-791f-41b8-9f47-45d98aa8c71e.png)

Maybe you could issue a warning about performance instead of blocking installation on systems with < 4?

### Why this request?

I think GhostBSD has matured to the point where most people will find it very easy to use and reliable.  Giving people with low-end hardware a chance to try it out will only increase adoption.

**Comment by ericbsd** [comment]
It is not a performance issue. It is a ram and installation issue.

You can't successfully install GhostBSD with less than 4G of ram, because GhostBSD is running in the ram and not from the USB. 

With the livecd pool loaded in the ram, it makes it impossible to install GhostBSD under 4G. 

Note after the livecd pool is loaded in the ram, the USB drive can be removed, and it is not needed to install GhostBSD.

Unfortunately, after 12 years working on GhostBSD, I have not found another stable way to do it. Unlike Linux, we don't have much choice for R/W live system.

The direction I took with the livecd won't work for everyone, and it is the price I was ready to pay for an R/W ZFS live filesystem.

**Comment by outpaddling** [comment]
Too bad...  Maybe you could add a notice in the installation guide (and the installer itself) informing users that the memory size of a VM can be reduced after installation?

Believing that a GhostBSD VM guest won't run on < 4 GiB would make me give up on it in some cases, but allocating 4 just for the duration of the install and reducing it to 2 after would be acceptable.

**Comment by outpaddling** [comment]
I did a fresh install with MATE under VirtualBox, then reduced the RAM to 1 GiB.  It basically worked fine, though update manager caused a lot of swapping and ran pretty slowly.  It runs pretty comfortably on 2 GiB.

FYI, I'm promoting GhostBSD to some of the less tech-savvy scientists I work with, so they can benefit from the nearly 2000 FreeBSD ports we have in the science categories.  Installing most or all of the tools they need via software station will help them realize that life can be simpler than the status quo of conda environments, containers, and cave-man installations.  I also maintain desktop-installer for slightly more seasoned Unix users.

**Comment by ericbsd** [comment]
There is already a warning on the download pages.
