### ISSUE TITLE
[Bug]: Lightdm not showing custom wallpaper on login

### ISSUE THREAD

**Issue by q-pa** [ghostbsd/ghostbsd-src#281]
### Version

23.04.02

### Explain the issue and what happens

Pre-set wallpapers work fine but custom wallpapers due to residing in $HOME do not show on login.

### Explain how to reproduce the bug?

Set custom wallpaper.

### What is the Expected behavior (if applicable)

To show user-set wallpapers accordingly.

**Comment by ericbsd** [comment]
The last update of lightdm started pointing to the current wallpapers in the home directory even if it can't access it.

By default, the home directory of a user is 700 on GhostBSD. It so looks like LightDM tries to set the wallpapers but can't even it can see them.

The code that is doing that is maintained by GhostBSD and was taken from Ubuntuthink. At the time I added the code default home directory was 755. So the cause of the issue is a directory permission issue.

The safest way would be to change the script to cache images in the user lightdm-data instead of changing the home permission. 

Also, updates can't and won't deal with the user's home folder permission. It is up to the user to manage it.

**Comment by ericbsd** [comment]
All that said I will come up with a fix to the script that manages user wallpapers for lightdm. As I said the script should cache images in the user lightdm-data. That way there is no permission to change and no crazy setup to do with unmask.

**Comment by ericbsd** [comment]
https://github.com/ghostbsd/ghostbsd-mate-settings/pull/1) should fix it for MATE.

**Comment by q-pa** [comment]
From the GhostBSD Telegram channel: (for Mate users it's just `cp /var/lib/dbus/machine-id /etc/machine-id` to make it worrk like before the last update)

Neville Goddard: To all GhostBSD xfce users who are having issues with their slick-greeter background here's a fix that worked for me. Apparantly a machine-id file is needed.
(Thanks Lennart)

Run as root

dbus-uuidgen --ensure

Then copy the machine-id to an appropriate location

cp /var/lib/dbus/machine-id /etc/machine-id

Make sure you have in /usr/local/etc/lightdm/slick-greeter.conf

[Greeter]
background=/path/to/your/picture.jpg
draw-user-backgrounds=false
