### ISSUE TITLE
Update Station won't update

### ISSUE THREAD

**Issue by BSD-1** [ghostbsd/ghostbsd-src#42]
When I run:
pkg query '%v' os-generic-userland-base

It returns:
20.12.25

Yet Update Station says no updates are available.

**Comment by ericbsd** [comment]
You are updated to date then. 

If you read the release notes, the version of the os is 20.12.25.

OS version and ISO version are not the same things.

We will probably stop calling them to release soon since we are a rolling release OS.

**Comment by outpaddling** [comment]
I've seen this issue several times now even though the system was not up-to-date.  Running

`pkg update`

from a terminal made Update Station recognize the need for updates.  I just used it again on a VM that has been shut down since July 4.  There are 116 packages to be upgraded, 4 new to install, 431 to reinstall.

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
