### ISSUE TITLE
[BUG] - Booting 21.05.11 ISO Failed to Startup in Desktop Environment

### ISSUE THREAD

**Issue by tekniculwiz** [ghostbsd/ghostbsd-src#77]
When booting GhostBSD 21.05.11 on VirtualBox on x64 Windows 10, the desktop environment is not starting up correctly due to an error in DBus that seems to stem from a typo. Seems to me it should probably be "SetBackgroundFiller".

Screenshot included.
![Screenshot doc_2021-06-09_22-00-30](https://user-images.githubusercontent.com/20852463/121468444-a616d880-c96f-11eb-89ff-6f7bd2a97261.png)

The following link provided in Telegram on GhostBSD group in response to post on Telegram posed as a question by user "Patrick" and problem experienced by user Kerry Jensen, as well: https://boringbsd.sgp1.digitaloceanspaces.com/GhostBSD-21.06.10-virtualbox-testing.iso

**Comment by ericbsd** [comment]
Looks like gksu problem

**Comment by ericbsd** [comment]
Fix an issue https://github.com/ghostbsd/ghostbsd-mate-settings/commit/c612579d7b0a930dd0fb551a9ada72cd23c7dbde

**Comment by ericbsd** [comment]
After more research and testing, the problem is not GhostBSD but VirtualBox. Virtualbox is forcing the VMSVGA graphics controller by default which is for Linux guests and not for FreeBSD guests. So VBOXBGA or VBOXSVGA graphics controller are to be selected.
Click on VMSVGA
![image](https://user-images.githubusercontent.com/4249848/131333895-bd8edeb9-89a1-4bd2-b7b5-ce1825ffb1c6.png)
Select VBOXBGA or VBOXSVGA and press OK.
![image](https://user-images.githubusercontent.com/4249848/131334868-f405dd8c-8742-4f76-83c2-7bccf45608c1.png)

**Comment by grahamperrin** [comment]
> VBOXVGA or VBOXSVGA

Better VBoxSVGA.

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
